// src/constants/readingJourneyContent.ts
import type { UnitContent } from '../types/readingJourney';

export const JOURNEY_UNITS: UnitContent[] = [
  {
    unitNumber: 1,
    title: 'Magic E',
    pattern: 'CVCe — silent E makes the vowel say its name',
    badgeId: 'UNICORN_MAGIC',
    words: [
      { word: 'cake', emoji: '🎂' },
      { word: 'bike', emoji: '🚲' },
      { word: 'home', emoji: '🏠' },
      { word: 'cute', emoji: '🐱' },
      { word: 'time', emoji: '⏰' },
      { word: 'rope', emoji: '🪢' },
      { word: 'late', emoji: '🌙' },
      { word: 'pine', emoji: '🌲' },
      { word: 'kite', emoji: '🪁' },
      { word: 'note', emoji: '📝' },
      { word: 'cube', emoji: '🧊' },
      { word: 'mole', emoji: '🐭' },
      { word: 'fame', emoji: '⭐' },
      { word: 'huge', emoji: '🐘' },
      { word: 'made', emoji: '🍰' },
    ],
    comprehensionItems: [
      {
        passage: 'Jake baked a big cake. He put it on the table at home.',
        question: 'What did Jake bake?',
        answer: 'a cake',
        choices: ['a cake', 'a kite', 'a note'],
      },
      {
        passage: 'I like to ride my bike. I ride it to the pine tree.',
        question: 'Where does she ride her bike?',
        answer: 'to the pine tree',
        choices: ['to the pine tree', 'to the lake', 'to the cube'],
      },
      {
        passage: 'The cute cat made a huge mess. It was late at night.',
        question: 'When did the cat make a mess?',
        answer: 'late at night',
        choices: ['late at night', 'at home', 'on the rope'],
      },
      {
        passage: 'She flew a kite on a rope. It went up and up in the sky.',
        question: 'What held the kite up?',
        answer: 'a rope',
        choices: ['a rope', 'a cube', 'a note'],
      },
      {
        passage: 'He wrote a note about his bike ride. It was a fun time.',
        question: 'What did he write about?',
        answer: 'his bike ride',
        choices: ['his bike ride', 'his kite', 'his home'],
      },
    ],
  },
  {
    unitNumber: 2,
    title: 'th / wh Words',
    pattern: 'Digraph reinforcement with richer vocabulary',
    badgeId: 'WHALE_WHISPERER',
    words: [
      { word: 'thick', emoji: '📏' },
      { word: 'thin', emoji: '🪡' },
      { word: 'three', emoji: '3️⃣' },
      { word: 'throw', emoji: '🥎' },
      { word: 'thumb', emoji: '👍' },
      { word: 'teeth', emoji: '🦷' },
      { word: 'cloth', emoji: '🧣' },
      { word: 'math', emoji: '🔢' },
      { word: 'bath', emoji: '🛁' },
      { word: 'whale', emoji: '🐋' },
      { word: 'wheat', emoji: '🌾' },
      { word: 'wheel', emoji: '⚙️' },
      { word: 'white', emoji: '🤍' },
      { word: 'whisper', emoji: '🤫' },
      { word: 'whistle', emoji: '🎵' },
    ],
    comprehensionItems: [
      {
        passage: 'The whale is white and very thick. It swims in the deep sea.',
        question: 'What color is the whale?',
        answer: 'white',
        choices: ['white', 'thin', 'wheat'],
      },
      {
        passage: 'Three thin kittens had a bath. They used a soft white cloth.',
        question: 'How many kittens had a bath?',
        answer: 'three',
        choices: ['three', 'thick', 'two'],
      },
      {
        passage: 'She whispered the math answer to her friend. They did not want to throw the test.',
        question: 'What did she whisper?',
        answer: 'the math answer',
        choices: ['the math answer', 'the wheel', 'the wheat'],
      },
      {
        passage: 'The thick wheel on the cart has three bolts. It does not throw off the cloth.',
        question: 'What is thick?',
        answer: 'the wheel',
        choices: ['the wheel', 'the whale', 'the bath'],
      },
      {
        passage: 'He blew the whistle with his thumb. The whole team could hear it.',
        question: 'What did he blow?',
        answer: 'the whistle',
        choices: ['the whistle', 'the wheel', 'the wheat'],
      },
    ],
  },
  {
    unitNumber: 3,
    title: 'Vowel Teams',
    pattern: 'CVVC — two vowels make one long sound',
    badgeId: 'MERMAID_VOWELS',
    words: [
      { word: 'rain', emoji: '🌧️' },
      { word: 'tail', emoji: '🦊' },
      { word: 'mail', emoji: '📬' },
      { word: 'braid', emoji: '💇' },
      { word: 'beat', emoji: '🥁' },
      { word: 'meat', emoji: '🥩' },
      { word: 'feet', emoji: '👣' },
      { word: 'seed', emoji: '🌱' },
      { word: 'tree', emoji: '🌳' },
      { word: 'boat', emoji: '⛵' },
      { word: 'coat', emoji: '🧥' },
      { word: 'road', emoji: '🛣️' },
      { word: 'pool', emoji: '🏊' },
      { word: 'food', emoji: '🍱' },
      { word: 'moon', emoji: '🌙' },
    ],
    comprehensionItems: [
      {
        passage: 'The rain fell on the green tree. The seed in the soil got a good drink.',
        question: 'What got a drink of water?',
        answer: 'the seed',
        choices: ['the seed', 'the boat', 'the coat'],
      },
      {
        passage: 'She put on her coat in the rain. Then she ran down the road to get the mail.',
        question: 'What did she wear in the rain?',
        answer: 'her coat',
        choices: ['her coat', 'her braid', 'her tail'],
      },
      {
        passage: 'A small boat floated on the pool under the moon. It had food on it.',
        question: 'Where was the boat?',
        answer: 'on the pool',
        choices: ['on the pool', 'on the road', 'on the tree'],
      },
      {
        passage: 'The fox wagged its tail and beat its feet on the road. It ran to find food.',
        question: 'What did the fox wag?',
        answer: 'its tail',
        choices: ['its tail', 'its coat', 'its braid'],
      },
      {
        passage: 'She braided her hair and ate some meat with her feet in the pool.',
        question: 'Where were her feet?',
        answer: 'in the pool',
        choices: ['in the pool', 'on the road', 'in the rain'],
      },
    ],
  },
  {
    unitNumber: 4,
    title: 'R-Controlled Vowels',
    pattern: 'R changes the vowel sound (ar, ir, er, or, ur)',
    badgeId: 'DRAGON_TAMER',
    words: [
      { word: 'car', emoji: '🚗' },
      { word: 'star', emoji: '⭐' },
      { word: 'farm', emoji: '🏡' },
      { word: 'bark', emoji: '🌳' },
      { word: 'jar', emoji: '🫙' },
      { word: 'bird', emoji: '🐦' },
      { word: 'girl', emoji: '👧' },
      { word: 'shirt', emoji: '👕' },
      { word: 'her', emoji: '👩' },
      { word: 'fern', emoji: '🌿' },
      { word: 'corn', emoji: '🌽' },
      { word: 'horn', emoji: '📯' },
      { word: 'storm', emoji: '⛈️' },
      { word: 'fur', emoji: '🦊' },
      { word: 'burn', emoji: '🔥' },
    ],
    comprehensionItems: [
      {
        passage: 'The girl wore her star shirt to the farm. She fed corn to the birds.',
        question: 'What did she wear to the farm?',
        answer: 'her star shirt',
        choices: ['her star shirt', 'her fur coat', 'her horn'],
      },
      {
        passage: 'A bird sat on the bark of the tree near the farm. It had brown fur.',
        question: 'Where did the bird sit?',
        answer: 'on the bark',
        choices: ['on the bark', 'in the jar', 'on the horn'],
      },
      {
        passage: 'The storm hit the farm hard. Her car got stuck in the mud near the barn.',
        question: 'What got stuck in the mud?',
        answer: 'her car',
        choices: ['her car', 'her fern', 'her shirt'],
      },
      {
        passage: 'She put a fern in a big jar. She kept it on the shelf near the horn.',
        question: 'Where did she put the fern?',
        answer: 'in a jar',
        choices: ['in a jar', 'in the car', 'on the farm'],
      },
      {
        passage: "The fur on the dog got a burn from the hot corn. It hurt a lot.",
        question: "What burned the dog's fur?",
        answer: 'the hot corn',
        choices: ['the hot corn', 'the storm', 'the bark'],
      },
    ],
  },
  {
    unitNumber: 5,
    title: 'Compound Words',
    pattern: 'Two smaller words joined into one new word',
    badgeId: 'WORD_WEAVER',
    words: [
      { word: 'sunshine', emoji: '☀️' },
      { word: 'cupcake', emoji: '🧁' },
      { word: 'football', emoji: '🏈' },
      { word: 'rainbow', emoji: '🌈' },
      { word: 'bedroom', emoji: '🛏️' },
      { word: 'butterfly', emoji: '🦋' },
      { word: 'lunchbox', emoji: '🍱' },
      { word: 'starfish', emoji: '⭐' },
      { word: 'treehouse', emoji: '🌳' },
      { word: 'birthday', emoji: '🎂' },
      { word: 'notebook', emoji: '📓' },
      { word: 'snowball', emoji: '⛄' },
      { word: 'popcorn', emoji: '🍿' },
      { word: 'firefly', emoji: '✨' },
      { word: 'sandbox', emoji: '🏖️' },
    ],
    comprehensionItems: [
      {
        passage: 'The sunshine made a rainbow in the sky. A butterfly flew under it.',
        question: 'What made the rainbow?',
        answer: 'the sunshine',
        choices: ['the sunshine', 'the firefly', 'the snowball'],
      },
      {
        passage: 'She got a notebook and a cupcake for her birthday. She put them in her bedroom.',
        question: 'What did she get for her birthday?',
        answer: 'a notebook and a cupcake',
        choices: ['a notebook and a cupcake', 'a football and a lunchbox', 'a treehouse and a sandbox'],
      },
      {
        passage: 'A firefly lit up the treehouse at night. The kids ate popcorn and watched it glow.',
        question: 'What did the firefly light up?',
        answer: 'the treehouse',
        choices: ['the treehouse', 'the sandbox', 'the bedroom'],
      },
      {
        passage: 'He packed a sandwich and popcorn in his lunchbox. He found a starfish near the sandbox.',
        question: 'What was in his lunchbox?',
        answer: 'a sandwich and popcorn',
        choices: ['a sandwich and popcorn', 'a cupcake and a notebook', 'a snowball and a football'],
      },
      {
        passage: 'The kids made a snowball and played football in the sunshine. Then they ate birthday cupcakes.',
        question: 'What did they make?',
        answer: 'a snowball',
        choices: ['a snowball', 'a lunchbox', 'a starfish'],
      },
    ],
  },
  {
    unitNumber: 6,
    title: 'Sight Words',
    pattern: "High-frequency words that don't follow phonics rules",
    badgeId: 'SIGHT_WORD_SORCERESS',
    words: [
      { word: 'said', emoji: '💬' },
      { word: 'come', emoji: '🚶' },
      { word: 'because', emoji: '💡' },
      { word: 'friend', emoji: '🤝' },
      { word: 'people', emoji: '👨‍👩‍👧' },
      { word: 'water', emoji: '💧' },
      { word: 'many', emoji: '🔢' },
      { word: 'where', emoji: '📍' },
      { word: 'were', emoji: '⏪' },
      { word: 'their', emoji: '👐' },
      { word: 'some', emoji: '🤏' },
      { word: 'have', emoji: '🫴' },
      { word: 'from', emoji: '📤' },
      { word: 'every', emoji: '🔄' },
      { word: 'could', emoji: '💪' },
    ],
    comprehensionItems: [
      {
        passage: 'She said she could come to the party. Many people were there from her school.',
        question: 'What did she say she could do?',
        answer: 'come to the party',
        choices: ['come to the party', 'have some water', 'go from there'],
      },
      {
        passage: 'People were thirsty because there was no water. Every friend had to come and help.',
        question: 'Why were people thirsty?',
        answer: 'there was no water',
        choices: ['there was no water', 'they were tired', 'their friend said so'],
      },
      {
        passage: 'She did not know where her friend was. She could have some help from her mom.',
        question: 'Who could help her?',
        answer: 'her mom',
        choices: ['her mom', 'every person', 'some water'],
      },
      {
        passage: 'Many people said the food from their friend was good. Every one of them could have some more.',
        question: 'What did people say about the food?',
        answer: 'it was good',
        choices: ['it was good', 'it was some water', 'it were from there'],
      },
      {
        passage: 'Their friend said come and have some water. People were happy because it was cold.',
        question: 'Why were people happy?',
        answer: 'the water was cold',
        choices: ['the water was cold', 'every friend were there', 'many could come'],
      },
    ],
  },
  {
    unitNumber: 7,
    title: 'Sentence Comprehension',
    pattern: 'Read mini-stories and answer questions',
    badgeId: 'STORY_QUEEN',
    words: [],
    comprehensionItems: [
      {
        passage: 'The whale swam in the deep pool. It made a big splash with its tail.',
        question: 'What did the whale make with its tail?',
        answer: 'a big splash',
        choices: ['a big splash', 'a rainbow', 'a snowball'],
      },
      {
        passage: 'The rainbow came after the rain. It had many bright colors in the sky.',
        question: 'When did the rainbow come?',
        answer: 'after the rain',
        choices: ['after the rain', 'before the rain', 'from the sunshine'],
      },
      {
        passage: 'She baked a cupcake for her friend. It was sweet and warm from the oven.',
        question: 'Who was the cupcake for?',
        answer: 'her friend',
        choices: ['her friend', 'her mom', 'her teacher'],
      },
      {
        passage: 'A firefly lit up the dark farm at night. It flew near the old barn by the corn.',
        question: 'Where did the firefly fly?',
        answer: 'near the old barn',
        choices: ['near the old barn', 'into the treehouse', 'over the pool'],
      },
      {
        passage: 'The girl wore her birthday crown all day long. She felt like a real princess.',
        question: 'How did she feel?',
        answer: 'like a real princess',
        choices: ['like a real princess', 'like a firefly', 'like a whale'],
      },
      {
        passage: 'The star was bright in the dark sky. Many people could see it from their bedroom window.',
        question: 'Where could people see the star from?',
        answer: 'their bedroom window',
        choices: ['their bedroom window', 'the farm', 'the pool'],
      },
      {
        passage: 'Her friend said come and play in the sunshine. They ran to the sandbox and made a big castle.',
        question: 'What did they make?',
        answer: 'a big castle',
        choices: ['a big castle', 'a snowball', 'a cupcake'],
      },
      {
        passage: 'The bird sang every morning from the tree. People said its song was sweet because it was so clear.',
        question: 'When did the bird sing?',
        answer: 'every morning',
        choices: ['every morning', 'at night', 'in the rain'],
      },
    ],
  },
];
