export const WORD_LISTS = {
  easy: [
    { word: 'cat', emoji: '🐱' },
    { word: 'dog', emoji: '🐶' },
    { word: 'sun', emoji: '☀️' },
    { word: 'hat', emoji: '🎩' },
    { word: 'cup', emoji: '🥤' },
    { word: 'bed', emoji: '🛏️' },
    { word: 'bug', emoji: '🐛' },
    { word: 'hen', emoji: '🐔' },
    { word: 'pig', emoji: '🐷' },
    { word: 'fox', emoji: '🦊' },
    { word: 'bat', emoji: '🦇' },
    { word: 'jam', emoji: '🍓' },
    { word: 'map', emoji: '🗺️' },
    { word: 'net', emoji: '🥅' },
    { word: 'pot', emoji: '🍲' },
  ],
  medium: [
    { word: 'boat', emoji: '⛵' },
    { word: 'frog', emoji: '🐸' },
    { word: 'play', emoji: '🎮' },
    { word: 'star', emoji: '⭐' },
    { word: 'blue', emoji: '🔵' },
    { word: 'tree', emoji: '🌳' },
    { word: 'rain', emoji: '🌧️' },
    { word: 'clap', emoji: '👏' },
    { word: 'flag', emoji: '🚩' },
    { word: 'swim', emoji: '🏊' },
    { word: 'drum', emoji: '🥁' },
    { word: 'drip', emoji: '💧' },
    { word: 'ship', emoji: '🚢' },
    { word: 'chip', emoji: '🍟' },
    { word: 'grip', emoji: '✊' },
  ],
  hard: [
    { word: 'bridge', emoji: '🌉' },
    { word: 'spring', emoji: '🌸' },
    { word: 'strong', emoji: '💪' },
    { word: 'splash', emoji: '💦' },
    { word: 'flower', emoji: '🌸' },
    { word: 'thunder', emoji: '⚡' },
    { word: 'blanket', emoji: '🛏️' },
    { word: 'chicken', emoji: '🐔' },
    { word: 'dolphin', emoji: '🐬' },
    { word: 'giraffe', emoji: '🦒' },
    { word: 'kitchen', emoji: '🍳' },
    { word: 'library', emoji: '📚' },
    { word: 'mittens', emoji: '🧤' },
    { word: 'penguin', emoji: '🐧' },
    { word: 'present', emoji: '🎁' },
  ],
};
